/*
  Simulador GPT educativo, escrito en JavaScript puro.
  La intención didáctica es mostrar los componentes reales de un LLM moderno
  con números pequeños y visualizaciones manejables para clase.
*/
const books = [
  { title: 'LIBRO 1 · LOS GATOS', lines: ['Los gatos son animales domésticos.', 'Los gatos tienen pelo.', 'Los gatos toman agua.', 'Los gatos pueden beber leche.', 'Los gatos son mascotas.'] },
  { title: 'LIBRO 2 · LOS PERROS', lines: ['Los perros son animales domésticos.', 'Los perros tienen pelo.', 'Los perros toman agua.', 'Los perros son mascotas.', 'Los perros ladran.'] },
  { title: 'LIBRO 3 · LOS ANIMALES', lines: ['Los animales necesitan agua.', 'Los animales necesitan alimento.', 'Los animales pueden ser mascotas.', 'Los animales tienen características físicas.'] }
];

const corpus = books.flatMap(book => book.lines).join(' ');
const cleanCorpus = corpus.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[¿?.,;]/g, '').replace(/\s+/g, ' ').trim();
const tokens = cleanCorpus.split(' ');
const vocabulary = [...new Set(tokens)].sort();
const tokenIds = Object.fromEntries(vocabulary.map((token, index) => [token, index + 1]));
const trainingExample = ['los', 'gatos', 'toman'];
let userQuestion = '¿Qué es un gato?';
let currentStep = 0;
let autoTimer = null;
let eventHistory = [];

const embeddings = Object.fromEntries(vocabulary.map((token, i) => [token, deterministicVector(i + 3, 100)]));
const learnedPositions = { gato: [31, 44], perro: [38, 47], animal: [52, 37], mascota: [45, 59], agua: [73, 68], leche: [78, 55] };
const initialPositions = { gato: [14, 20], perro: [74, 18], animal: [49, 76], mascota: [22, 70], agua: [82, 42], leche: [35, 35] };
const stageMeta = {
  'Módulo A': { label: 'Entrenamiento', tone: 'learn', detail: 'Los pasos se ejecutan en orden. Aquí sí puede haber pérdida, gradientes y actualización de pesos.' },
  'Módulo B': { label: 'Inferencia', tone: 'infer', detail: 'Los pasos también son secuenciales. No se entrenan pesos: se reutiliza lo aprendido.' },
  'Módulo C': { label: 'Comparación', tone: 'compare', detail: 'Resumen final para contrastar qué ocurre y qué no ocurre en cada modo.' }
};

function deterministicVector(seed, dims) {
  return Array.from({ length: dims }, (_, i) => Number((Math.sin(seed * (i + 1)) * 0.72).toFixed(2)));
}
function list(items) { return `<ul class="mini-list">${items.map(item => `<li>${item}</li>`).join('')}</ul>`; }
function callout(title, body) { return `<div class="callout"><strong>${title}</strong><span>${body}</span></div>`; }
function tokenChips(words) { return `<div class="token-row">${words.map(w => `<span class="token">${w}<br><span class="id">ID ${tokenIds[w] || 'UNK'}</span></span>`).join('')}</div>`; }
function vectorPreview(word) { const v = embeddings[word] || deterministicVector(word.length, 100); return `<article class="vector-card"><strong>${word}</strong><div class="embedding">${v.slice(0, 60).map(x => `<span title="${x}" style="opacity:${Math.abs(x) + .18}; background:${x >= 0 ? 'var(--accent)' : 'var(--accent-2)'}"></span>`).join('')}</div><small>Vista parcial: [${v.slice(0, 6).join(', ')}, ... 100 valores]</small></article>`; }
function probabilityBars(items) { return `<div class="prob-list">${items.map(([name, value]) => `<div class="bar"><label><span>${name}</span><b>${value}%</b></label><div class="meter"><span style="width:${value}%"></span></div></div>`).join('')}</div>`; }
function attentionMatrix(words) { return `<table class="matrix"><tr><th></th>${words.map(w => `<th>${w}</th>`).join('')}</tr>${words.map((r, i) => `<tr><th>${r}</th>${words.map((_, j) => `<td class="${i === j || (r === 'gatos' && j === 2) || (r === 'gato' && j === 1) ? 'hot' : ''}">${(0.12 + (i === j ? .52 : 0) + (j === 2 ? .18 : 0)).toFixed(2)}</td>`).join('')}</tr>`).join('')}</table>`; }
function space(points, title) { return `<div class="space-wrap"><h3>${title}</h3><div class="space">${Object.entries(points).map(([name, [x,y]]) => `<span class="point" style="left:${x}%;top:${y}%"><label>${name}</label></span>`).join('')}</div></div>`; }
function state(changing = false) { return `<div class="state-grid"><div><span>Tokens</span><b>${tokens.length}</b></div><div><span>Vocabulario</span><b>${vocabulary.length}</b></div><div><span>Embedding</span><b>100D</b></div><div><span>Pesos</span><b class="${changing ? 'changed' : 'frozen'}">${changing ? 'Actualizándose' : 'Congelados'}</b></div></div><p class="state-note">${changing ? 'El modelo está aprendiendo: la pérdida envía gradientes hacia los parámetros.' : 'Solo se leen datos o se hace inferencia; los parámetros permanecen iguales.'}</p>`; }
function weights(changing = false) { const rows = [['Embedding gato', .51, changing ? .49 : .51, 'mueve el significado de “gato”'], ['Atención Q', .23, changing ? .20 : .23, 'cambia qué busca cada token'], ['Atención V', -.18, changing ? -.12 : -.18, 'cambia qué información se transmite']]; return `<div class="weights">${rows.map(([n,a,b,desc]) => `<div class="weight ${a!==b?'active-weight':''}"><b>${n}</b><p>${a} → <span class="${a!==b?'changed':'frozen'}">${b}</span></p><small>${desc}</small></div>`).join('')}</div><p class="state-note">${changing ? 'En este paso los números se actualizan porque existe un gradiente calculado desde el error.' : 'Estos valores están visibles para entender qué se modificaría, pero ahora no cambian.'}</p>`; }
function mathBox(formula, goal, params = []) { return `<div class="formula"><code>${formula}</code></div><div class="math-help"><p><b>¿Para qué sirve?</b> ${goal}</p>${params.length ? `<p><b>Parámetros:</b></p>${list(params)}` : ''}</div>`; }
function flow(nodes, arrows = '→') { return `<div class="flow">${nodes.map((n, i) => `<span class="node">${n}</span>${i < nodes.length - 1 ? `<span class="arrow">${arrows}</span>` : ''}`).join('')}</div>`; }

const phases = [
  { m:'Módulo A', t:'Construcción del conocimiento', e:'Se parte de textos humanos. El objetivo es formar una base de datos pequeña para observar patrones repetidos.', v:()=>`<div class="book-grid">${books.map(b=>`<div class="book"><h3>${b.title}</h3>${b.lines.map(l=>`<p>${l}</p>`).join('')}</div>`).join('')}</div>${callout('Idea clave','Todavía no hay IA: solo documentos que luego serán convertidos en números.')}`, math:()=>mathBox('Datos brutos = documentos escritos por humanos', 'Define la materia prima antes del aprendizaje.', ['documentos: libros o frases disponibles', 'datos brutos: texto sin procesar']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo A', t:'Creación del corpus', e:'El corpus une los documentos en una colección. Es la materia prima que se limpiará y tokenizará.', v:()=>`${flow(['Libro 1','Libro 2','Libro 3','Corpus'],'+') }<p class="text-sample">${corpus}</p>`, math:()=>mathBox('Corpus = D₁ ∪ D₂ ∪ D₃', 'Agrupa varias fuentes en una sola colección entrenable.', ['D₁, D₂, D₃: documentos individuales', '∪: unión/colección de textos']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo A', t:'Preprocesamiento', e:'Se reducen variaciones superficiales: mayúsculas, acentos, puntuación y espacios duplicados.', v:()=>`<div class="before-after"><div><h3>Antes</h3><p>${corpus}</p></div><div><h3>Después</h3><p>${cleanCorpus}</p></div></div>`, math:()=>mathBox('lowercase(text) → remove(puntuación) → tokens limpios', 'Hace que palabras equivalentes se representen de forma consistente.', ['text: corpus original', 'tokens limpios: palabras normalizadas']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo A', t:'Tokenización', e:'Cada palabra se transforma en un token con ID. El modelo operará con índices y vectores, no con significado humano directo.', v:()=>tokenChips(['los','gatos','son','animales','domesticos']), math:()=>mathBox(`los=${tokenIds.los}, gatos=${tokenIds.gatos}, son=${tokenIds.son}`, 'Convierte texto en identificadores numéricos que pueden buscarse en tablas.', ['token: palabra o fragmento', 'ID: posición del token en el vocabulario']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo A', t:'Vocabulario', e:'El vocabulario delimita qué símbolos conoce este simulador. Todo token debe existir aquí o se marca como desconocido.', v:()=>`<div class="token-row compact">${vocabulary.map(w=>`<span class="token">${w}<br><span class="id">${tokenIds[w]}</span></span>`).join('')}</div>`, math:()=>mathBox(`|V| = ${vocabulary.length}`, 'Cuenta cuántos tokens distintos puede reconocer el modelo.', ['V: conjunto de tokens conocidos', '|V|: tamaño del vocabulario']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo A', t:'Inicialización aleatoria', e:'Los embeddings nacen como coordenadas ajustables. Al inicio no representan significado útil.', v:()=>`${vectorPreview('gatos')}${vectorPreview('perros')}`, math:()=>mathBox('E[token] ∈ ℝ¹⁰⁰', 'Representa cada token como un vector de 100 números.', ['E: matriz de embeddings', 'token: ID usado para elegir una fila', 'ℝ¹⁰⁰: vector de 100 dimensiones']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo A', t:'Creación de ejemplos', e:'El entrenamiento causal enseña a predecir el siguiente token a partir de los anteriores.', v:()=>`<div class="cards"><div class="card">Entrada: Los<br><b>Objetivo: gatos</b></div><div class="card">Entrada: Los gatos<br><b>Objetivo: son</b></div><div class="card">Entrada: Los gatos toman<br><b>Objetivo: agua</b></div></div>`, math:()=>mathBox('P(xₜ | x₁,...,xₜ₋₁)', 'Calcula la probabilidad del siguiente token dada la historia previa.', ['xₜ: token objetivo', 'x₁...xₜ₋₁: contexto anterior']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo A', t:'Embeddings', e:'El ID selecciona una fila de la matriz E. Esa fila podrá acercarse a palabras con contextos similares.', v:()=>trainingExample.map(vectorPreview).join(''), math:()=>mathBox('xᵢ = E[idᵢ]', 'Obtiene el vector que entra al Transformer.', ['idᵢ: ID del token i', 'E: tabla aprendible', 'xᵢ: vector resultante']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo A', t:'Forward pass', e:'Los vectores pasan por el Transformer para generar puntajes llamados logits. Aún no se corrigen pesos.', v:()=>flow([...trainingExample, 'Transformer', 'Logits']), math:()=>mathBox('logits = Transformer(E[los,gatos,toman])', 'Produce puntajes antes de convertirlos a probabilidades.', ['E[...]: embeddings de entrada', 'Transformer: capas de atención', 'logits: puntajes sin normalizar']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo A', t:'Self attention', e:'La atención decide qué tokens importan para entender cada posición. Aquí “toman” mira a “gatos” para anticipar un objeto plausible.', v:()=>attentionMatrix(trainingExample), math:()=>mathBox('Attention(Q,K,V)=softmax(QKᵀ/√dₖ)V', 'Mezcla información de tokens relevantes.', ['Q: lo que cada token busca', 'K: lo que cada token ofrece para ser encontrado', 'V: información que se transmite', 'dₖ: escala para estabilizar puntajes']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo A', t:'Predicción', e:'El modelo asigna probabilidades. En este ejemplo se equivoca: prefiere “leche” aunque el objetivo es “agua”.', v:()=>probabilityBars([['agua',20],['leche',50],['animal',15],['pelo',15]])+'<p class="verdict bad">Predicción: leche · Correcto: agua</p>', math:()=>mathBox('argmax(P)=leche, y*=agua', 'Elige el token con probabilidad más alta y lo compara con el objetivo.', ['P: distribución de probabilidades', 'argmax: posición con mayor valor', 'y*: respuesta correcta']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo A', t:'Softmax', e:'Softmax convierte logits en probabilidades comparables que suman 1.', v:()=>probabilityBars([['agua',20],['leche',50],['animal',15],['pelo',15]]), math:()=>mathBox('softmax(zᵢ)=e^{zᵢ}/Σⱼe^{zⱼ}', 'Normaliza puntajes para interpretar la salida como porcentajes.', ['zᵢ: puntaje del token i', 'Σⱼ: suma sobre todos los tokens candidatos']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo A', t:'Función de pérdida', e:'La entropía cruzada mide qué tan mal fue asignar baja probabilidad al token correcto.', v:()=>`<div class="card hero-metric"><h3>Cross Entropy Loss</h3><b>0.91</b><span>porque P(agua)=0.40</span></div>`, math:()=>mathBox('L = -Σ yᵢ log(pᵢ)', 'Produce un número de error que el optimizador intentará reducir.', ['L: pérdida/error', 'yᵢ: etiqueta correcta', 'pᵢ: probabilidad predicha']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo A', t:'Gradientes', e:'El gradiente indica en qué dirección cambiaría la pérdida si movemos cada parámetro.', v:()=>`<div class="cards"><div class="card changed">Embedding gato<br><small>señal alta</small></div><div class="card changed">Atención Q<br><small>señal media</small></div><div class="card changed">Atención V<br><small>señal media</small></div></div>`, math:()=>mathBox('∂L/∂θ', 'Mide la sensibilidad del error respecto a cada peso.', ['L: pérdida', 'θ: cualquier parámetro', '∂: cambio infinitesimal']), s:()=>state(true), p:()=>weights(false) },
  { m:'Módulo A', t:'Backpropagation', e:'La retropropagación lleva la señal de error desde la salida hacia capas anteriores usando la regla de la cadena.', v:()=>flow(['Loss','Softmax','Transformer','Embeddings'],'←'), math:()=>mathBox('∂L/∂θ₁ = (∂L/∂h)(∂h/∂θ₁)', 'Calcula gradientes en capas profundas a partir de efectos encadenados.', ['h: activación intermedia', 'θ₁: parámetro temprano']), s:()=>state(true), p:()=>weights(false) },
  { m:'Módulo A', t:'Actualización de pesos', e:'El optimizador modifica parámetros: resta una pequeña parte del gradiente. Aquí ocurre el aprendizaje.', v:()=>weights(true), math:()=>mathBox('θₙᵤₑᵥₒ = θ - η∇θL', 'Actualiza el peso para reducir el error en el próximo intento.', ['θ: peso actual', 'η: learning rate o tamaño del paso', '∇θL: gradiente de la pérdida']), s:()=>state(true), p:()=>weights(true) },
  { m:'Módulo A', t:'Epochs', e:'Una epoch recorre el dataset completo. Repetir epochs suele bajar la pérdida si el modelo aprende patrones útiles.', v:()=>`<div class="loss-chart">${[[1,.91],[2,.70],[3,.42],[4,.20],[5,.05]].map(([e,l])=>`<div class="loss-bar" style="height:${l*170}px"><small>E${e}<br>${l}</small></div>`).join('')}</div>`, math:()=>mathBox('Loss media: 0.91 → 0.70 → 0.42 → 0.20 → 0.05', 'Muestra si el entrenamiento va reduciendo el error.', ['epoch: pasada completa por el dataset', 'loss media: error promedio']), s:()=>state(true), p:()=>weights(true) },
  { m:'Módulo A', t:'Embeddings aprendidos', e:'Gato y perro terminan cerca porque aparecen en contextos parecidos: domésticos, pelo, agua y mascotas.', v:()=>`<div class="space-grid">${space(initialPositions,'Antes')}${space(learnedPositions,'Después')}</div>`, math:()=>mathBox('sim(gato, perro)=cos(e_gato,e_perro)', 'Mide cercanía semántica mediante ángulo entre vectores.', ['e_gato/e_perro: embeddings aprendidos', 'cos: similitud de coseno']), s:()=>state(false), p:()=>weights(true) },
  { m:'Módulo A', t:'Modelo entrenado', e:'Tras entrenar, los parámetros quedan listos para inferencia. La consulta no debe modificar pesos.', v:()=>`<div class="cards"><div class="card"><h3>Tokens</h3>${tokens.length}</div><div class="card"><h3>Parámetros didácticos</h3>${vocabulary.length * 100}</div><div class="card"><h3>Epochs</h3>5</div><div class="card"><h3>Loss final</h3>0.05</div></div>`, math:()=>mathBox('θ* = parámetros entrenados y congelados', 'Guarda el resultado del entrenamiento para responder consultas.', ['θ*: conjunto final de pesos']), s:()=>state(false), p:()=>weights(true) },
  { m:'Módulo B', t:'Consulta: tokenización', e:'La pregunta del usuario se convierte en tokens. En inferencia no hay etiqueta objetivo ni pérdida de entrenamiento.', v:()=>tokenChips(tokenizeQuestion()), math:()=>mathBox('IDs consulta = ['+tokenizeQuestion().map(w=>tokenIds[w]||'UNK').join(', ')+']', 'Convierte el prompt en índices que el modelo puede procesar.', ['UNK: token desconocido', 'IDs consulta: secuencia de entrada']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo B', t:'Consulta: embeddings', e:'Los tokens recuperan vectores aprendidos. Esos vectores se leen, no se reentrenan.', v:()=>tokenizeQuestion().map(vectorPreview).join(''), math:()=>mathBox('x_consulta = E_congelado[ids]', 'Obtiene vectores para representar la pregunta.', ['E_congelado: embeddings ya entrenados', 'ids: tokens de la consulta']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo B', t:'Positional encoding', e:'El modelo necesita orden para distinguir frases con las mismas palabras en posiciones distintas.', v:()=>`<table class="matrix"><tr><th>Token</th><th>Posición</th><th>Entrada al bloque</th></tr>${tokenizeQuestion().map((w,i)=>`<tr><td>${w}</td><td>${i}</td><td>x${i}+PE${i}</td></tr>`).join('')}</table>`, math:()=>mathBox('hᵢ⁰ = E[tokenᵢ] + PE(i)', 'Suma significado del token más información de posición.', ['E[tokenᵢ]: embedding', 'PE(i): vector de posición', 'hᵢ⁰: entrada inicial contextualizada']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo B', t:'Self attention en consulta', e:'La palabra “gato” concentra peso porque contiene la entidad principal de la pregunta.', v:()=>attentionMatrix(tokenizeQuestion()), math:()=>mathBox('pesos atención ≈ gato 0.80, qué 0.10, es 0.05, un 0.05', 'Estima qué partes del prompt aportan más contexto.', ['peso: importancia relativa', 'gato: entidad central consultada']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo B', t:'Query, Key, Value', e:'Q pregunta qué buscar, K anuncia qué contiene cada token y V transporta la información que se mezclará.', v:()=>`<div class="qkv-grid">${tokenizeQuestion().map(w=>`<div class="card"><h3>${w}</h3><p>Q: busca</p><p>K: etiqueta</p><p>V: contenido</p></div>`).join('')}</div>`, math:()=>mathBox('Q=Wq·x, K=Wk·x, V=Wv·x', 'Proyecta cada embedding en tres roles para atención.', ['Wq/Wk/Wv: matrices aprendidas', 'x: vector del token', 'Q/K/V: vectores resultantes']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo B', t:'Transformer contextual', e:'El Transformer produce representaciones dependientes del contexto. La misma palabra puede cambiar de sentido según sus vecinas.', v:()=>`<div class="cards"><div class="card">banco + dinero → entidad financiera</div><div class="card">banco + parque → asiento</div></div>`, math:()=>mathBox('hᵢᴸ = TransformerBlock(...TransformerBlock(hᵢ⁰))', 'Refina el significado de cada token a través de varias capas.', ['hᵢ⁰: entrada inicial', 'hᵢᴸ: salida final de la última capa', 'L: número de capas']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo B', t:'Softmax de salida', e:'La capa final estima el siguiente token más probable. Aún no hay respuesta completa: solo la próxima pieza.', v:()=>probabilityBars([['animal',60],['mascota',20],['felino',15],['otro',5]]), math:()=>mathBox('P(siguiente token | pregunta) = softmax(W_out h)', 'Convierte la representación final en probabilidades de salida.', ['W_out: matriz de salida', 'h: estado contextual final']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo B', t:'Generación autorregresiva', e:'Cada token generado se añade al contexto y se repite el forward pass. Por eso la respuesta aparece palabra por palabra.', v:()=>flow(['Un','gato','es','un','animal','doméstico','fin']), math:()=>mathBox('xₜ₊₁ ~ P(· | x₁...xₜ)', 'Muestrea o elige el próximo token condicionado por lo ya escrito.', ['xₜ₊₁: nuevo token', 'x₁...xₜ: contexto acumulado']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo B', t:'Respuesta final', e:'Durante inferencia no hay loss, gradiente, backpropagation ni actualización. Solo se repite forward pass con pesos congelados.', v:()=>`<div class="card response-card"><h3>Respuesta generada</h3><p>Un gato es un animal doméstico que puede ser mascota, tiene pelo y toma agua.</p></div>`, math:()=>mathBox('Solo forward pass repetido; θ permanece constante', 'Aclara que responder no equivale a aprender nuevos pesos.', ['θ: pesos del modelo', 'constante: no cambia durante la consulta']), s:()=>state(false), p:()=>weights(false) },
  { m:'Módulo C', t:'Comparación entrenamiento vs inferencia', e:'Entrenamiento ajusta parámetros usando objetivos y gradientes. Inferencia reutiliza parámetros congelados para generar predicciones.', v:()=>`<table class="compare"><tr><th>Aspecto</th><th>Entrenamiento</th><th>Inferencia</th></tr>${[['Dataset','Sí, corpus convertido en ejemplos','No, solo prompt del usuario'],['Loss','Sí','No'],['Gradiente','Sí','No'],['Backpropagation','Sí','No'],['Actualización de parámetros','Sí','No'],['Aprendizaje','Sí','No'],['Predicción','Sí, para medir error','Sí, para responder'],['Ejecución','Costosa y repetida','Rápida por consulta']].map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</table>`, math:()=>mathBox('Entrenar: minimizar L(θ). Inferir: calcular P(y|x,θ*)', 'Resume la diferencia central entre aprender y responder.', ['L(θ): error según pesos', 'P(y|x,θ*): probabilidad de respuesta con pesos finales']), s:()=>state(false), p:()=>weights(false) }
];

function tokenizeQuestion() { return userQuestion.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[¿?]/g, ' ?').replace(/[.,;]/g, '').trim().split(/\s+/).filter(Boolean); }
function renderStepper() {
  const phase = phases[currentStep];
  const meta = stageMeta[phase.m];
  stepper.innerHTML = phases.map((p, i) => `<button data-step="${i}" class="${i === currentStep ? 'active' : ''} ${i < currentStep ? 'done' : ''}" title="${i + 1}. ${p.t}"><span>${i + 1}</span></button>`).join('');
  stepSummary.innerHTML = `<b>${meta.label}</b><span>${meta.detail}</span>`;
}
function render() {
  const phase = phases[currentStep];
  moduleBadge.textContent = phase.m;
  phaseTitle.textContent = phase.t;
  phaseCounter.textContent = `Paso ${currentStep + 1} de ${phases.length}`;
  explanation.innerHTML = `<p>${phase.e}</p>${callout('Qué debes observar', stageMeta[phase.m].detail)}`;
  visualization.innerHTML = phase.v();
  mathPanel.innerHTML = phase.math();
  statePanel.innerHTML = phase.s();
  paramsPanel.innerHTML = phase.p();
  const progress = Math.round((currentStep / (phases.length - 1)) * 100);
  progressBar.value = progress;
  progressText.textContent = `${progress}%`;
  renderStepper();
  addEvent(phase);
}
function addEvent(phase) {
  eventHistory.unshift({ time: new Date().toLocaleTimeString(), step: currentStep + 1, module: phase.m, title: phase.t, mode: stageMeta[phase.m].label });
  eventHistory = eventHistory.slice(0, 6);
  eventLog.innerHTML = eventHistory.map((e, index) => `<li class="${index === 0 ? 'current' : ''}"><span class="event-step">${e.step}</span><div><b>${e.title}</b><small>${e.time} · ${e.mode} · ejecución secuencial</small></div></li>`).join('');
}
function buildStepper() { stepper.addEventListener('click', e => { const button = e.target.closest('button[data-step]'); if (button) { currentStep = Number(button.dataset.step); render(); } }); }
function stopAuto() { clearInterval(autoTimer); autoTimer = null; autoBtn.textContent = 'Autoejecución'; }

prevBtn.onclick = () => { currentStep = Math.max(0, currentStep - 1); render(); };
nextBtn.onclick = () => { currentStep = Math.min(phases.length - 1, currentStep + 1); render(); };
resetBtn.onclick = () => { stopAuto(); currentStep = 0; eventHistory = []; render(); };
autoBtn.onclick = () => { if (autoTimer) return stopAuto(); autoBtn.textContent = 'Pausar autoejecución'; autoTimer = setInterval(() => { if (currentStep >= phases.length - 1) return stopAuto(); currentStep += 1; render(); }, Number(speedSelect.value)); };
speedSelect.onchange = () => { if (autoTimer) { stopAuto(); autoBtn.click(); } };
applyQuestion.onclick = () => { userQuestion = document.getElementById('userQuestion').value || '¿Qué es un gato?'; render(); };

buildStepper();
render();
